name: CD

on:
  push:
    branches:
      - 'feature/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Set up AWS Serverless
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: |
          npm install -g serverless
          serverless config credentials --provider aws --key ${{ secrets.AWS_KEY }} --secret ${{ secrets.AWS_SECRET }}
      - name: Install depedencies
        run: composer install -vvv
      - name: Copy parameter from development
        run: |
          echo "${{ secrets.PARAMS }}" >> params.php
#          mkdir ~/.ssh && cd ~/.ssh && echo "${{ secrets.SSH_KEY }}" >> id_rsa && chmod 400 id_rsa && ssh-keygen -y -f ~/.ssh/id_rsa >> id_rsa.pub && chmod 644 id_rsa.pub
#          ssh-agent /bin/sh && ssh-add ~/.ssh/id_rsa
#          ssh-keygen -R api.doogether.tech
#          scp root@api.doogether.tech:/home/admin/api/core/config/params-local.php .
#        uses: appleboy/scp-action@master
#        with:
#          username: root
#          host: api.doogether.tech
#          key: ${{ secrets.SSH_KEY }}
#          source: "/home/admin/api/core/config/params-local.php"
#          target: "config"
      - name: Deploy to Lambda
        run: serverless deploy